### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by jordanwillis** [bdrinkh2o/TomeRater#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4
* _Comment(s):_ Great job writing valid python code without any errors!
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4
* _Comment(s):_ All of the necessary project requirements were correctly implemeneted and looked great!  I also enjoyed the various comments that you r
 
### Criteria 3: Software Architecture
* _Score Level:_
* _Comment(s):_
 
### Criteria 4: Uses Python Language Features
* _Score Level:_
* _Comment(s):_ Great job using many build-in language feature and functions!  I jotted down a few notes while doing the review and wanted to share them with you.

1.  Make sure you understand the difference between between class and instance variables and when it's best to use them.

https://github.com/bdrinkh2o/TomeRater/blob/d01d663da36edb8bbeccb5ca6a7aebdd5fe9e772/TomeRater.py#L54-L60

Instance variables are the variables declared in your `__init__` using `self` (e.g. `self.title`, etc.).  With this type of variable, each new instance of the class `Book` will have their own separate variables.  Class variables on the other hand are declared directly within the class (like shown above), and *every* instance of the class will share the *same* variable.  I know there is a good chance that you already understand this, but every time I see a student use a class variable I like to re-explain it.

So the implication of this design choice is that every single `Book` instance that gets created shares a single `isbn_list` variable between them all, thus it is a good way to check for duplicates across your instances.  So nicely done!!

2. I liked the added formating using `.title()` provides, but I would recommend actually storing it that way instead of just returning/printing.

https://github.com/bdrinkh2o/TomeRater/blob/d01d663da36edb8bbeccb5ca6a7aebdd5fe9e772/TomeRater.py#L63-L65

The reason for this is we don't want things to become inconsistent.  So if I created a new `Book` with a title of "welcome home" and then later see that the title returned is "Welcome Home", then I am not sure if it got converted internally our just formated for printing.  I might have a check in my code that says...

``` python
if my_bool.getTitle() == "welcome home":
    # do something
```

and this would confuse me if it didn't return true.  So long story short, don't change the format on print or return, change it on creation.

3. You can simplify your methods that return true/false by just returning from the condition.

https://github.com/bdrinkh2o/TomeRater/blob/d01d663da36edb8bbeccb5ca6a7aebdd5fe9e772/TomeRater.py#L86-L90

``` python
def __eq__(self, new_book):
    return (self.isbn == new_book.isbn) and (self.title == new_book.title)
```

This is just an example, but a nice way to further mature your code.
 
### Overall Score: 16/16
Overall you did an outstanding job on this project!  I can tell that you learned a lot from the course and put in a good effort to end up with a great solution.  Keep up the great work!

**Comment by bdrinkh2o** [comment]
Hi Jordan,

(Sorry so for the late reply) - Thank you so much for your review!   I enjoyed your notes and I especially liked the explanation of class/instance variables.  It helped drive that point home.  Thank you!  

all the best

--brian
